config/routes.rb
Rails.application.routes.draw do
  get 'puntuacions/recarregar'
  get 'puntuacions/esborrar'
  get 'puntuacions/esborrar_tot'
  get 'puntuacions/grava_puntuacio'
  get 'home/espera'
  get 'taller2', to: 'home#taller2', as: :taller2
  get 'talleracasa', to: 'home#talleracasa', as: :talleracasa
  get 'casa', to: 'home#casa', as: :casa
  get 'video', to: 'home#video', as: :video
  get 'home/index'
  get 'fases/canvi_fase_2'
  get 'fases/canvi_fase'
  resources :puntuacions
  resources :estats
  resources :missatges
  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/missatge.rb
class Missatge < ApplicationRecord
  belongs_to :user
end

app/models/puntuacio.rb
class Puntuacio < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    [first_name, last_name].compact.join(' ')
  end

  validates :first_name, :presence => true
  validates :last_name, :presence => true

  has_many :puntuacions, dependent: :destroy
  has_many :missatges, dependent: :destroy

  def self.online
    ids = ActionCable.server.pubsub.redis_connection_for_subscriptions.smembers "online"
    where(id: ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/fases_controller.rb
class FasesController < ApplicationController
  def canvi_fase
  	ActionCable.server.broadcast "stage_channel", stage_id: params[:fase]
  end

  def canvi_fase_2
  	ActionCable.server.broadcast "stage_channel", stage_id: params[:fase]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index, :taller2, :casa, :talleracasa]
  
  def index
  	@missatge = Missatge.new
    @missatges = Missatge.all
    
  end

  def taller2
    @missatge = Missatge.new
    @missatges = Missatge.all
  end

  def video
  	@video = 'wHiat6z6W00dCJjlnoLnx5Fln2mzR9bnuWRIlHeSjZ01E'
  end

  def casa
  	@missatge = Missatge.new
    @missatges = Missatge.all
    @video = 'wHiat6z6W00dCJjlnoLnx5Fln2mzR9bnuWRIlHeSjZ01E'
  end

  def talleracasa
    @missatge = Missatge.new
    @missatges = Missatge.all
    @video = 'wHiat6z6W00dCJjlnoLnx5Fln2mzR9bnuWRIlHeSjZ01E'
  end
end

app/controllers/missatges_controller.rb
class MissatgesController < ApplicationController
  before_action :set_missatge, only: [:show, :edit, :update, :destroy]

  # GET /missatges
  # GET /missatges.json
  def index
    @missatges = Missatge.all
  end

  # GET /missatges/1
  # GET /missatges/1.json
  def show
  end

  # GET /missatges/new
  def new
    @missatge = Missatge.new
  end

  # GET /missatges/1/edit
  def edit
  end

  # POST /missatges
  # POST /missatges.json
  def create
    @missatge = Missatge.create(missatge_params)
    if @missatge.save
      ActionCable.server.broadcast "room_channel", user_id: @missatge.user_id, nom: current_user.first_name, contingut: @missatge.contingut
    else
    end
  end

  # PATCH/PUT /missatges/1
  # PATCH/PUT /missatges/1.json
  def update
    respond_to do |format|
      if @missatge.update(missatge_params)
        format.html { redirect_to @missatge, notice: 'Missatge was successfully updated.' }
        format.json { render :show, status: :ok, location: @missatge }
      else
        format.html { render :edit }
        format.json { render json: @missatge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missatges/1
  # DELETE /missatges/1.json
  def destroy
    @missatge.destroy
    respond_to do |format|
      format.html { redirect_to missatges_url, notice: 'Missatge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_missatge
      @missatge = Missatge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def missatge_params
      params.require(:missatge).permit(:user_id, :contingut)
    end
end

app/controllers/puntuacions_controller.rb
class PuntuacionsController < ApplicationController
  def index
    @puntuacions_fase1 = Puntuacio.where(fase: 1)
    @puntuacions_fase2 = Puntuacio.where(fase: 2)
    @puntuacions_fase3 = Puntuacio.where(fase: 3)
    @puntuacions_fase4 = Puntuacio.where(fase: 4)
    @puntuacions_fase5 = Puntuacio.where(fase: 5)
    @puntuacions_fase6 = Puntuacio.where(fase: 6)
    @puntuacions_fase7 = Puntuacio.where(fase: 7)
    @puntuacions_fase8 = Puntuacio.where(fase: 8)
    @puntuacions_fase9 = Puntuacio.where(fase: 9)
    @puntuacions_fase10 = Puntuacio.where(fase: 10)
    @puntuacions_fase11 = Puntuacio.where(fase: 11)
    @puntuacions_fase12 = Puntuacio.where(fase: 12)
    @puntuacions_fase13 = Puntuacio.where(fase: 13)
    @puntuacions_fase14 = Puntuacio.where(fase: 14)
    @puntuacions_fase15 = Puntuacio.where(fase: 15)
    @puntuacions_fase16 = Puntuacio.where(fase: 16)

    # Aquí fer query per tenir llistat d'usuaris amb suma de puntuacions
    usuaris = User.all
    @llistat_usuaris = Array.new
    usuaris.each do |u|
      nom = u.first_name + ' ' + u.last_name
      puntuacions_positives = u.puntuacions.where(correcte: true)
      puntuacions_positives_uniques = puntuacions_positives.map(&:fase).uniq
      nombre_positius = puntuacions_positives_uniques.count
      @llistat_usuaris.push [nom, nombre_positius]
    end
    
  end

  def create
    @puntuacio = Puntuacio.create(puntuacio_params)
    @puntuacio.user_id = current_user.id
    @puntuacio.save
  end

  def grava_puntuacio
    @puntuacio = Puntuacio.new
    @puntuacio.user_id = current_user.id
    @puntuacio.fase = params[:fase].to_i
    if params[:correcte] == 'true'
      @puntuacio.correcte = true
    else
      @puntuacio.correcte = false
    end
    @puntuacio.save
  end

  def esborrar
  end

  def recarregar
    redirect_to puntuacions_path
  end

  def esborrar_tot
    users = User.all
    users.each do |u|
      u.destroy
    end
    redirect_to puntuacions_path
  end

  private
    def puntuacio_params
      params.require(:puntuacio).permit(:fase, :correcte)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fases_helper.rb
module FasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/missatges_helper.rb
module MissatgesHelper
end

app/helpers/puntuacions_helper.rb
module PuntuacionsHelper
end

app/views/fases/_desena.html.erb
<div id="container-fase-10" class="container-fase">
	<h1 class="titol-repte">Tria la millor opció per estalviar energia</h1>
	<p>Podem estalviar molta energia amb les petites decisions que prenem cada dia!</p>
	
	<div id="container-tria-aventura-1">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>En Joan engega tots els llums</p>
			</div>
			<%= image_tag "llum_artificial.jpg", class: "tria-aventura", id: "llum-artificial" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>En Joan aprofita la llum del Sol</p>
			</div>
			<%= image_tag "llum_natural.jpg", class: "tria-aventura", id: "llum-natural" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-2">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Paula agafa ràpid el que necessita i torna a tancar la nevera</p>
			</div>
			<%= image_tag "nevera_be.jpg", class: "tria-aventura", id: "nevera-be" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Paula deixa la nevera oberta molta estona mentre decideix què vol agafar</p>
			</div>
			<%= image_tag "nevera_malament.jpg", class: "tria-aventura", id: "nevera-malament" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-3">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Marta va poc abrigada i han de pujar la calefacció a l'escola</p>
			</div>
			<%= image_tag "classe_fred.jpg", class: "tria-aventura", id: "classe-fred" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Marta va ben vestida per no tenir fred encara que sigui hivern</p>
			</div>
			<%= image_tag "classe_be.jpg", class: "tria-aventura", id: "classe-be" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-4">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>L'Anna torna de la feina amb el cotxe</p>
			</div>
			<%= image_tag "transport_cotxe.jpg", class: "tria-aventura", id: "transport-cotxe" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>L'Anna torna de la feina amb la bicicleta</p>
			</div>
			<%= image_tag "transport_bici.jpg", class: "tria-aventura", id: "transport-bici" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-5">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>Després de rentar la roba l'estén per que s'assequi</p>
			</div>
			<%= image_tag "roba_estesa.jpg", class: "tria-aventura", id: "roba-estesa" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>Després de rentar la roba la posa a l'assecadora</p>
			</div>
			<%= image_tag "roba_assecadora.jpg", class: "tria-aventura", id: "roba-assecadora" %>
			
		</div>
	</div>

	<div class="benomalfet10">
		<p class="benfet10"><%= image_tag "correcte.png", class: "correcte" %></p>
		<p class="malfet10"><%= image_tag "nocorrecte.png", class: "nocorrecte" %></p>
	</div>
</div>

app/views/fases/_indefinida.html.erb
<div id="container-fase-2" class="container-fase">
	<ul id="sortable">
	  <li class="ui-state-default">1</li>
	  <li class="ui-state-default">2</li>
	  <li class="ui-state-default">3</li>
	  <li class="ui-state-default">4</li>
	  <li class="ui-state-default">5</li>
	  <li class="ui-state-default">6</li>
	  <li class="ui-state-default">7</li>
	  <li class="ui-state-default">8</li>
	  <li class="ui-state-default">9</li>
	  <li class="ui-state-default">10</li>
	  <li class="ui-state-default">11</li>
	  <li class="ui-state-default">12</li>
	</ul>
</div>

app/views/fases/_primera.html.erb
<div id="container-fase-1" class="container-fase">
  <h1 class="titol-repte">El repte de les lletres perdudes</h1>
  <br/>
  <p class="text-repte">Per què és important estalviar energia a casa?</p>
  <p id="frase-1" class="repte-lletres-perdudes">P_r _st_lv__r d_n_rs _ ll__t_r c_ntr_ _l c_nv_ cl_m_t_c.</p>
  <p id="frase-2" class="repte-lletres-perdudes">P_r _sta</span>lv_a</span>r d_n_rs _ ll__ta</span>r c_ntra</span> _l ca</span>nv_ cl_mà</span>t_c.</p>
  <button id="pista-1" class="btn boto-accio">Necessito una pista</button>

  <br/>
  <br/>
  <p class="text-repte">Escriu la resposta aquí:</p>
  <input id="input-repte-1"></input>
  <button id="comprova-repte-1" class="btn boto-accio">Comprova</button>
  <p class="benfet"><%= image_tag "correcte.png", class: "correcte" %> </p>
  <p class="malfet"><%= image_tag "nocorrecte.png", class: "nocorrecte" %></p>
</div>

app/views/fases/_setena.html.erb
<div id="container-fase-7" class="container-fase">
	<h1 class="titol-repte">Solar tèrmica i solar fotovoltaica</h1>
	<p>Els panells solars s'assemblen però no són iguals! <br/>Col·loca sobre els panells el que produeixen.</p>
	<div class="container-panells-solars">
		<div id="container-panell-solar-termic">
			<%= image_tag "panell_termic.jpg", class: "panells-solars", id: "panell-termic" %>
			<%= image_tag "panell_termic_ok.jpg", class: "panells-solars", id: "panell-termic-ok" %>
		</div>
		<div id="container-panell-solar-fotovoltaic">
			<%= image_tag "panell_fotovoltaic.jpg", class: "panells-solars", id: "panell-fotovoltaic" %>
			<%= image_tag "panell_fotovoltaic_ok.jpg", class: "panells-solars", id: "panell-fotovoltaic-ok" %>
		</div>
	</div>
	<div class="container-clear"></div>

	<div class="container-produccions">
		<div id="produccio-1" class="requadre-produccio">
		  <%= image_tag "aigua_freda.jpg", class: "imatge-produccio" %>
		</div>
		<div id="produccio-2" class="requadre-produccio">
		  <%= image_tag "slime.jpg", class: "imatge-produccio" %>
		</div>
		<div id="produccio-3" class="requadre-produccio">
		  <%= image_tag "aigua_calenta.jpg", class: "imatge-produccio" %>
		</div>
		<div id="produccio-4" class="requadre-produccio">
		  <%= image_tag "crispetes.jpg", class: "imatge-produccio" %>
		</div>
		<div id="produccio-5" class="requadre-produccio">
		  <%= image_tag "electricitat.jpg", class: "imatge-produccio" %>
		</div>
	</div>

	<div class="container-clear"></div>

	<p class="benfet7"><%= image_tag "correcte.png", class: "correcte" %></p>
  
</div>

app/views/fases/_taller2_f13.html.erb
<div id="container-fase-13" class="container-fase">
  <h1 class="titol-repte">Memòria prodigiosa</h1>
  <br/>
  <p class="text-repte">Escriu els valors mínims d'il·luminació en lux per a cada espai:</p>
  
  <br/>
  <label>Aula:</label>
  <input id="input1-repte-13"></input>
  <br/>
  <label>Gimnàs:</label>
  <input id="input2-repte-13"></input>
  <br/>
  <label>Biblioteca:</label>
  <input id="input3-repte-13"></input>
  <br/>
  <label>Passadís:</label>
  <input id="input4-repte-13"></input>
  <br/>
  <br/>
  <button id="comprova-repte-13" class="btn boto-accio">Comprova</button>
  <p class="benfet13"><%= image_tag "correcte.png", class: "correcte" %> </p>
  <p class="malfet13"><%= image_tag "nocorrecte.png", class: "nocorrecte" %></p>
</div>

app/views/fases/canvi_fase.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="inici-sessio-container">
			<h2>Control del taller</h2>
			<p><%= link_to "Fase 1", fases_canvi_fase_path(fase: '1') %>: Les lletres perdudes</p>
			<p><%= link_to "Fase 2", fases_canvi_fase_path(fase: '2') %>: On és l'illa de Pasqua</p>
			<p><%= link_to "Fase 3", fases_canvi_fase_path(fase: '3') %>: De què estan fetes les cases</p>
			<p><%= link_to "Fase 4", fases_canvi_fase_path(fase: '4') %>: Els tres porquets</p>
			<p><%= link_to "Fase 5", fases_canvi_fase_path(fase: '5') %>: Estufa o manta</p>
			<p><%= link_to "Fase 7", fases_canvi_fase_path(fase: '7') %>: Solar tèrmica o fotovoltaica</p>
			<p><%= link_to "Fase 8", fases_canvi_fase_path(fase: '8') %>: Puzzle la frase amagada</p>
			<p><%= link_to "Fase 9", fases_canvi_fase_path(fase: '9') %>: Rehabilitació energètica</p>
			
			<p><%= link_to "Fase 10", fases_canvi_fase_path(fase: '10') %>: Tria la teva aventura</p>
			<p><%= link_to "Fase 11", fases_canvi_fase_path(fase: '11') %>: Una frase amagada</p>
			<p><%= link_to "Fase 12", fases_canvi_fase_path(fase: '12') %>: Quanta llum necessitem?</p>
			<p><%= link_to "Fase 13", fases_canvi_fase_path(fase: '13') %>: Memòria prodigiosa</p>
			<p><%= link_to "Fase 14", fases_canvi_fase_path(fase: '14') %>: Quanta llum necessitem? (2)</p>
			<p><%= link_to "Fase 15", fases_canvi_fase_path(fase: '15') %>: Quanta llum necessitem? (3)</p>
			<p><%= link_to "Fase 16", fases_canvi_fase_path(fase: '16') %>: Seguim les instruccions</p>

			<p><%= link_to "Amagar-ho tot", fases_canvi_fase_path(fase: '0') %></p>
			
		</div>
	</div>
	
	
</div>

app/views/home/espera.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="inici-sessio-container">
      <p>Següent taller:<br/>
      <span class="sala-espera-text"><%= @estat.anunci %></span></p>

      <br/>
      <br/>
      <div class="sala-espera-entrar">
        <% if @estat.obert == false %>
          <p>Encara no es pot entrar</p>
          <p><%= link_to "Torna a comprovar si es pot entrar", home_espera_path %></p>
        <% else %>
          <%= link_to "Entrar", home_index_path, class: 'btn boto-accio' %>
        <% end %>
      </div>
      <br/>
      <br/>
    </div>
  </div>
</div>

app/views/layouts/enblanc.html.erb
<%= yield %>

app/views/missatges/edit.html.erb
<h1>Editing Missatge</h1>

<%= render 'form', missatge: @missatge %>

<%= link_to 'Show', @missatge %> |
<%= link_to 'Back', missatges_path %>

app/views/missatges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Missatges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Contingut</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @missatges.each do |missatge| %>
      <tr>
        <td><%= missatge.user_id %></td>
        <td><%= missatge.contingut %></td>
        <td><%= link_to 'Show', missatge %></td>
        <td><%= link_to 'Edit', edit_missatge_path(missatge) %></td>
        <td><%= link_to 'Destroy', missatge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Missatge', new_missatge_path %>

app/views/missatges/new.html.erb
<h1>New Missatge</h1>

<%= render 'form', missatge: @missatge %>

<%= link_to 'Back', missatges_path %>

app/views/missatges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @missatge.user_id %>
</p>

<p>
  <strong>Contingut:</strong>
  <%= @missatge.contingut %>
</p>

<%= link_to 'Edit', edit_missatge_path(@missatge) %> |
<%= link_to 'Back', missatges_path %>

app/views/puntuacions/esborrar.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="inici-sessio-container">
      Segur que ho vols esborrar tot?
      <%= link_to "Esborrar tots els usuaris i puntuacions", puntuacions_esborrar_tot_path, class: 'btn boto-accio' %>
    </div>
  </div>
</div>

app/views/puntuacions/index.html.erb
<% 
def classe_li(correcte)
  if correcte == true 
    li_class = "puntuacio-positiva"
  else
    li_class = "puntuacio-negativa"
  end
  return li_class
end

def text_resultat(correcte)
  if correcte == true 
    resultat = "Sí"
  else
    resultat = "No"
  end
  return resultat
end
%>

<div class="row">
	<div class="col-md-6">
		<div class="inici-sessio-container">
      <h1>Puntuacions</h1>
      <p>Fase 1:</p>
      <ul>
      <% @puntuacions_fase1.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 2:</p>
      <ul>
      <% @puntuacions_fase2.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 3:</p>
      <ul>
      <% @puntuacions_fase3.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 4:</p>
      <ul>
      <% @puntuacions_fase4.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 5:</p>
      <ul>
      <% @puntuacions_fase5.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 6:</p>
      <ul>
      <% @puntuacions_fase6.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 7:</p>
      <ul>
      <% @puntuacions_fase7.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 8:</p>
      <ul>
      <% @puntuacions_fase8.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 9:</p>
      <ul>
      <% @puntuacions_fase9.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 10:</p>
      <ul>
      <% @puntuacions_fase10.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 11:</p>
      <ul>
      <% @puntuacions_fase11.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 12:</p>
      <ul>
      <% @puntuacions_fase12.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 13:</p>
      <ul>
      <% @puntuacions_fase13.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 14:</p>
      <ul>
      <% @puntuacions_fase14.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 15:</p>
      <ul>
      <% @puntuacions_fase15.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
      <p>Fase 16:</p>
      <ul>
      <% @puntuacions_fase16.each do |punt| %>
        <% usuari = User.find_by(id: punt.user_id) %>
        <li class="<%= classe_li(punt.correcte) %>"><%= usuari.first_name %> <%= usuari.last_name %>: <%= text_resultat(punt.correcte) %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-6">
		<div class="inici-sessio-container">
      <div class="inici-sessio-container">
        <%= link_to "Esborrar informació", puntuacions_esborrar_path, class: 'btn boto-accio' %>
        <%= link_to "Actualitzar", puntuacions_recarregar_path, class: 'btn boto-accio' %>
      </div>

      <% 
      max_puntuacio = 0
      guanyador = ''
      @llistat_usuaris.each do |u|  
        if u[1] >= max_puntuacio
          max_puntuacio = u[1]
          guanyador = u[0]
        end
      end 
      %>
      <ul>
      <% @llistat_usuaris.each do |u| %>
        <% if u[1] == max_puntuacio %>   
          <li class="champion"><%= u[0] %>: <%= u[1] %> </li>
        <% else %>
          <li><%= u[0] %>: <%= u[1] %> </li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
	<div class="footer-container">
		©2021 CAATEEB
	</div>
</footer>

app/views/users/_online.html.erb
<div class="item-usuari" data-id="<%= user.id %>">
	<div class="indicador-usuari-online"></div><%= user.name %><div id="check-usuari-<%= user.id %>"></div>
</div>